### ISSUE TITLE
Brother, what kind of project is this?

### ISSUE THREAD

**Issue by zhaoguohao** [dandizarrs/27964c5b-6ccd-4e23-a67d-a535282bab34#1]

**Comment by yarikoptic** [comment]
Thanks for asking -- I added a little more info to the profile of https://github.com/dandizarrs but discover more at https://github.com/dandisets and overall project is https://dandiarchive.org/ .

This particular repo is a DataLad dataset for a single zarr file within some dataset of https://dandiarchive.org/ . You can fetch data using DataLad or git-annex directly if you just git clone it.

**Comment by zhaoguohao** [comment]
> [感谢您的询问——我在https://github.com/dandizarrs](https://github.com/dandizarrs)的个人资料中添加了更多信息，但在https://github.com/dandisets上发现了更多信息，整个项目是https://dandiarchive.org/。
> 
> 这个特定的 repo 是一个 DataLad 数据集，用于https://dandiarchive.org/的某个数据集中的单个 zarr 文件。如果你只是 git clone 它，你可以直接使用 DataLad 或 git-annex 获取数据。

cool, I noticed that there seems to be optical imaging of human brains in the warehouse, by the way, is there any data research on brain atrophy

**Comment by yarikoptic** [comment]
not in our archive I believe. Sister archive  has at least one related MRI (or are you interested only in misroscopy?) dataset - https://openneuro.org/datasets/ds003052/versions/1.1.0 , I bet there is more MRI if to look for MS or Alzheimer data

**Comment by zhaoguohao** [comment]
> 我相信不在我们的档案中。姐妹档案至少有一个相关的 MRI（或者你只对微观检查感兴趣？）数据集 - https://openneuro.org/datasets/ds003052/versions/1.1.0，我敢打赌如果要寻找 MS 或者有更多的 MRI老年痴呆症数据

thanks a lot bro
